config/routes.rb
Rails.application.routes.draw do
  get 'categories/new'
  devise_for :users
  root to: "searches#index"
  # NOTE! once the path exists change to >> root to: "searches#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"

  resources :searches do
    resources :bookmarks, only: %i[create]
    resources :reviews, only: %i[create]
  end
  
  resources :bookmarks, only: %i[index show destroy] do
    post "/bookmarks_categories", to: "bookmark_categories#create", as: :categories
  end
  
  resources :user_categories, only: %i[new create destroy]
  resources :reviews, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :search
  has_many :bookmark_categories, dependent: :destroy
  has_many :categories, through: :bookmark_categories, source: :user_category
end

app/models/bookmark_category.rb
class BookmarkCategory < ApplicationRecord
  belongs_to :bookmark
  belongs_to :user_category
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :website
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :website
  has_many :reviews, through: :website

  def website_url
    website.website_url
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :categories, class_name: "UserCategory"
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_uniqueness_of :email, :username
  validates_presence_of :email, :username
end

app/models/user_category.rb
class UserCategory < ApplicationRecord
  belongs_to :user
  has_many :bookmark_categories, dependent: :destroy
  has_many :bookmarks, through: :bookmark_categories
end

app/models/website.rb
class Website < ApplicationRecord
  has_many :searches
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookmark_categories_controller.rb
class BookmarkCategoriesController < ApplicationController
  before_action :set_bookmark_categories, only: :destroy
  before_action :set_user_categories, only: %i[new create]

  def new
    @bookmark_category = BookmarkCategory.new
  end

  def create
    @bookmark_category = BookmarkCategory.new
    @bookmark = Bookmark.find(params[:bookmark_id])
    @bookmark_category.user_category = @user_category
    @bookmark_category.bookmark = @bookmark
    if @bookmark_category.save
      redirect_to bookmarks_path
    else
      redirect_to bookmarks_path, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark_category.destroy
    redirect_to user_category_path(@bookmark_category.user_category), status: :see_other
  end

  private

  def bookmark_category_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_bookmark_categories
    @bookmark = BookmarkCategory.find(params[:id])
  end

  def set_user_categories
    @user_category = UserCategory.find(params[:user_category_id])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmarks, except: %i[index create destroy]
  before_action :set_search, only: %i[create]

  def index
    @bookmarks = Bookmark.where(user: current_user)

    @bookmarks = @bookmarks.select { |p| p.categories.ids.include?(params[:category].to_i) } if params[:category].present?
    respond_to do |format|
      format.html
      format.text { render partial: "bookmarks", locals: {bookmarks: @bookmarks }, formats: [:html] }
    end
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new
    @bookmark.user = current_user
    @bookmark.search = @search
    if @bookmark.save
      redirect_to bookmarks_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to bookmarks_path, status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:search_id)
  end

  def set_search
    @search = Search.find(params[:search_id])
  end

  def set_bookmarks
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @search = Search.find(params[:search_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.website = @search.website
    if @review.save
      redirect_to search_path(@search)
    else
      redirect_to search_path(@search), status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    @search = Search.find(params[:search_id])
    redirect_to search_path(@search)
  end

  def review_params
    params.require(:review).permit(:comment)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @searches = Search.where("rating>=7").limit(3)
  end

  def create
    query = clean_up_url(params["query"].downcase) if params["query"].present?
    @website = Website.find_by(website_url: query) || Website.create(website_url: query)
    @search = Search.where(website: @website)&.last

    unless @search.present? && @search.updated_at < 30.days.ago
      @search = Search.new
      @search.website = @website
      @search.trustpilot_verification = TrustpilotService.new(query).trustpilot.present?
      @search.scamdoc_score = ScamdocService.new(query).scamdoc_score
      @search.https = ScamdocService.new(query).https_presence
      if scamdoc_weight.nil?
        @search.rating = nil
      else
        @search.rating = scamdoc_weight + trustpilot_weight
      end
      @search.save
    end

    if @search.id
      redirect_to search_path(@search)
    else
      render 'index'
    end
  end

  def show
    @search = Search.find(params[:id])
    @review = Review.new(website: @website)
  end

  private

  def search_params
    params.require(:search).permit(:website_name, :website_url, :trustpilot_verification, :scandoc, :https, :rating)
  end

  def scamdoc_weight
    if @search.scamdoc_score.nil? || @search.scamdoc_score > 90
      @search.scamdoc_score
    else
      @search.scamdoc_score * 0.8
    end
  end

  def trustpilot_weight
    if @search.trustpilot_verification == true && @search.scamdoc_score <= 90
      @trustpilot_score = 20
    else
      @trustpilot_score = 0
    end
  end

  def clean_up_url(url)
    url.match?(/www./) ? url.gsub(/www./, "") : url
  end
end

app/controllers/user_categories_controller.rb
class UserCategoriesController < ApplicationController
  def new
    @user_category = UserCategory.new(user: current_user)
  end

  def create
    @user_category = UserCategory.new(category_params)
    @user_category.user = current_user
    if @user_category.save
      redirect_to bookmarks_path
    else
      render 'new'
    end
  end

  def destroy
    @user_category = UserCategory.find(params[:id])
    @user_category.destroy
    redirect_to bookmarks_path, status: :see_other
  end

  private

  def category_params
    params.require(:user_category).permit(:name)
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  def index
    @websites = Website.all
  end

  def show
    @website = Website.find(params[:id])
  end

  def create
    @website = Website.all.find { |e| e.website_url == params["query"] }
    unless @website.present?
      @website = Search.new
      @website.website_url = params["query"]
      @website.save
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookmarks/_bookmarks.html.erb
<div style="text-align:center" class= "mt-3 mb-5";>
  <%= link_to "Create Category", new_user_category_path, class: "btn-green" %>
</div>

<% bookmarks.each do |bookmark| %>
      <div class="accordion" id="accordionExample_<%= dom_id(bookmark) %>">
        <div class="accordion-item">
          <h2 class="accordion-header" id="header_<%= dom_id(bookmark) %>">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_<%= dom_id(bookmark) %>" aria-expanded="false" aria-controls="collapse_<%= dom_id(bookmark) %>">
              <p> <%= bookmark.search.website_url %></p>
            </button>
          </h2>
          <div id="collapse_<%= dom_id(bookmark) %>" class="accordion-collapse collapse" aria-labelledby="header_<%= dom_id(bookmark) %>" data-bs-parent="#accordionExample_<%= dom_id(bookmark) %>">
            <div class="accordion-body">
              <p>Your watson rating is: <strong><%= bookmark.search.rating %></strong></p>
              <p> <% if bookmark.search.https == true %>
                    HTTPS protocol detected
                  <% else %>
                  No HTTPS protocol detected
                  <% end %>
              </p>
              <p> <% if bookmark.search.trustpilot_verification == true%>
                     Verified company on Trustpilot
                  <% else %>
                      Not verified on Trustpilot
                  <% end %>
              </p>
            </div>
            <div class="form-bookmark">
              <%= form_with url: bookmark_categories_path(bookmark), method: :post do |f| %>
                <%= f.select :user_category_id, current_user.categories.map {|m| [m.name, m.id]} %>
                <%= f.submit "Add to Category" %>
              <%end %>
              <%= link_to " ", bookmark_path(bookmark), class: "fa-regular fa-trash-can", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this bookmark?"}%>
            </div>
          </div>
        </div>
      </div>
<% end %>

  <div style="text-align:center" class= "mt-5";>
    <%= link_to "Search again", searches_path, class: "btn-green" %>
  </div>

app/views/bookmarks/index.html.erb
<div class="wrapper justify-content-center col-12 col-md-6 col-lg-4 py-3" data-controller="bookmark-matches">
  <h2>Hello, <strong><%= current_user.username %></strong></h2>
  <h2 data-bookmark-matches-target="name" class="text-center pb-3">Bookmarks:</h2>


  <div class="category-cards">
    <%current_user.categories.each do |category| %>
    <div class="category-card">
      <div  data-action="click->bookmark-matches#filter">
        <%= link_to category.name.truncate(20), bookmarks_path(category: category) %>
      </div>
      <div>
        <%= link_to "", user_category_path(category), class: "fa-regular fa-trash-can", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this category?"} %>
      </div>
    </div>
  <% end %>
  </div>

  <p>You have <strong><%= @bookmarks.count %> bookmarks</strong> in total</p>
  <div class="accordion bookmarks py-1" id="accordionExample" data-bookmark-matches-target="bookmarksHolder">
     <%= render "bookmarks", bookmarks: @bookmarks %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watson - shop safely</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag "favicon_3.png", rel: "icon", type: "image/png" %>

  </head>

  <body class="text-center row justify-content-center <%= "cream-background" if devise_controller? || params[:controller] == "bookmarks"  %>" >

 <%# <div style="text-align: center;">
    <%= link_to searches_path, class: 'logo' do %
    <%= image_tag "mainlogo", width: "100%" %
    <% end %
  </div> %>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/home_search_animation.html.erb
<div class="searching">
  <h1>Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
  <h2 class="animated-text" data-text="Analaysing...">Analaysing...</h2>
  <div class="spinner">
  </div>
  <%= image_tag "search.png", alt: "search" %>
</div>

app/views/searches/index.html.erb
<div class="wrapper" data-controller="search" >

  <div class="display-search pt-5" data-search-target="displaySearch" style="
    height: 350px;">
    <div class="searching">
       <h2 class="animated-text show-page-font" data-text="Analysing..."><strong>Analysing...</strong></h2>
    </div>
    <div class="glass-position">
      <div class="spinner">
      </div>
      <%= image_tag "search_v2.png", class: "glass", alt: "search", width: "270px" %>
    </div>
  </div>

  <div class="front-container">
    <div class="display-slogan" data-search-target="displaySlogan">
      <div class="slogan" >
        <h1>We check the <br><strong><span>red flags.</span></strong>
        <br>You shop <strong>
        <br><span>safely.</span></strong></h1>
      </div>

      <div>
        <%= form_with url: "/searches", method: :post, data: { search_target: "mainSearch" } do |form| %>
        <div class ="d-flex justify-content-center">
          <%= form.text_field :query, class: "form-input" %>
          <%= button_tag content_tag(:div, content_tag(:i, "", class:"fa-solid fa-magnifying-glass"), class: "circle"), type: "submit", data: { action: "click->search#displaySearch" }, id: "lupa" %>
          <% end %>
        </div>
        <p id= info-search> Write your shop's <strong>web address</strong> above</p>
      </div>
          <div class="thinline">
      </div>

      <div class="index-card" style="margin: 10px 10px;">
        <p id=top-searches> Top <strong>3</strong> searches:</p>
        <% @searches.each do |search| %>
          <%= link_to search_path(search) do %>
          <div class="show-card d-flex justify-content-between">
            <p> <strong><%=search.website.website_url%></strong></p>
            <%# <p> <%=website_url %</p>
            <%# <p>Rating: <%= search.rating % >/10 </p> %>
            <div>
              <%= button_tag content_tag(:div, content_tag(:i, "", class:"fa-solid fa-arrow-right"), class: "circle"), id: "arrow" %>
            </div>
          </div>
          <% end %>
        <% end %>
      </div>

      <div class="line">
      </div>

    </div>

  </div>

</div>

app/views/searches/show.html.erb
<div class="wrapper">
   <div class="watson-rating-card mt-3 bg-white">
    <h2 class="show-page-font">You searched</h2>
    <h3 class="show-page-font"><strong>'<%=@search.website_url %>'</strong></h3>
    <% if @search.rating == nil %>
     <i class="fa-solid fa-question", id="question"></i>
      <p class="show-page-font mt-3 mb-5">We couldn't find this domain. Please verify your input. </p>
    <% elsif @search.rating > 59 %>
      <i class="fa-regular fa-thumbs-up", id="thumbs-up"></i>
      <p class="show-page-font mt-3 mb-5">Rating score: <strong> <%= @search.rating %>% safe </strong></p>
    <% else %>
      <i class="fa-regular fa-thumbs-down", id="thumbs-down"></i>
      <p class="show-page-font mt-3 mb-5">Rating score: <strong> <%= @search.rating %>% safe</strong></p>
    <% end %>
  </div>


  <% if @search.rating.nil? %>
  <div class="domain-error">
  <% else %>
  <div>
  <% end %>
    <div style="text-align:center" >
      <p style="text-align:center;">Add this search to your bookmarks:</strong></p>
      <%= link_to "Save search", search_bookmarks_path(@search), data: {turbo_method: :post}, class:"btn-green" %>
    </div>

    <div class="thinline mt-5">
    </div>

    <h2 style="text-align:center;" class="mt-5">Read more details:</strong></h2>

      <div class="card-container">
        <div class="accordion" id="accordionExample">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingThree">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                <% if @search.https == true %>
                HTTPS protocol detected
                <% else %>
                No HTTPS protocol detected
                <% end %>
              </button>
            </h2>
            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                Hypertext transfer protocol secure (HTTPS) is the secure version of HTTP, which is the primary protocol used to send data between a web browser and a website. HTTPS is encrypted in order to increase security of data transfer.
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                <% if @search.trustpilot_verification == true %>
                Verified company on Trustpilot
                <% else %>
                Not verified on Trustpilot
                <% end %>
              </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <a href="https://www.trustpilot.com/" target="_blank">Trustpilot</a> is a digital platform that allows customers to review a business from which they've purchased a product or service or contacted customer service.
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                ScamDoc Score : <%= @search.scamdoc_score %> / 99
              </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <a href="https://www.scamdoc.com/" target="_blank">Scamdoc</a> is a web tool that evaluates "digital identities" reliability.
              </div>
            </div>
          </div>
        </div>
      </div>

    <div class="thinline mt-5">
    </div>

    <div class="text-align:center">
          <h2>Reviews:</h2>
          <% if @search.reviews.empty? %>
            <small><em class="text-muted">Be the first one to review this shop</em></small>
          <% end %>
          <% @search.reviews.each do |review| %>
            <div class= "reviews">
              <small> <em class="text-muted"> review by <%= review.user.username %></em>,</small>
              <small> <em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
              <p class="mb-0"><%= review.comment %></p>
                <% if review.user == current_user %>
                  <%= link_to "", review_path(review,search_id: @search.id), class: "fa-regular fa-trash-can", data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this review?" } %>
                <% end %>
            </div>
            <hr>
          <% end %>
    </div>


    <div class="text-align:center">
          <div class="bg-white rounded p-3">
            <%= simple_form_for [@search, @review] do |f| %>
              <%= f.input :comment, label: false, placeholder: "Add your review here..." %>
              <%= f.submit class:"btn btn-blue" %>
            <% end %>
          </div>
    </div>

    <div class="thinline mt-4">
    </div>

  </div>

  <div style="text-align:center" class= "mt-5";>
    <%= link_to "Search again", searches_path, class: "btn-green" %>
  </div>

  <div class="line">
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <%= link_to "/searches", class: "navbar-brand" do %>
    <%= image_tag "mainlogo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My bookmarks", bookmarks_path, class: "nav-link" %>
             <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/user_categories/new.html.erb
<div class="login-form-container">
  <h2>Create Category</h2>
  <%= simple_form_for [@user_category] do |f| %>
    <%= f.input :name %>
    <%= f.submit "Submit", class: "btn btn-green" %>
  <% end %>
</div>